### ISSUE TITLE
运行GenLibs.bat报“系统找不到指定的批处理标签”

### ISSUE THREAD

**Issue by funcman** [gongminmin/UniversalDXSDK#1]
Git会转换文本换行符，如果bat脚本被转为Unix文本，则bat脚本中的标签会失效。

有没有办法规避？PowerShell？

:)

**Comment by gongminmin** [comment]
需要再安装tortoisegit的时候选择”Checkout Windows-style, commit Unix-style line endings“，或者在系统的.gitconfig里面加上
[core]
	autocrlf = true
这样就能自动调整换行符。

**Comment by gongminmin** [comment]
增加了个.gitattributes，强制bat的eol方式。
