### ISSUE TITLE
GPL license

### ISSUE THREAD

**Issue by Lssikkes** [gongminmin/UniversalDXSDK#2]
Why the GPL license? This way this can't be used for (commercial) closed source products. Wouldn't a BSD or MIT license be better for such a library?

**Comment by gongminmin** [comment]
Thanks for your feedback. I do consider to switch to MIT license here. It'll be done very soon.

**Comment by Lssikkes** [comment]
Awesome, thank you! Your work is much appreciated, getting extremely tired having to rely on the windows SDK, but I need to be able to include this everywhere without having to worry about the license.. Keep up the good work :)
