### ISSUE TITLE
Any doc for using def in cmake?

### ISSUE THREAD

**Issue by RPG3D** [gongminmin/UniversalDXSDK#5]
`if(MSVC)
  set(CMAKE_EXE_LINKER_FLAGS
      "${CMAKE_EXE_LINKER_FLAGS} /DEF:${CMAKE_CURRENT_SOURCE_DIR}/../ThirdParty/UniversalDXSDK/Def/d3dxof.def")
endif()
add_executable(TestApp ${PRIVATE_SOURCES})`

got error
`2>d3dxof.def : error LNK2001: unresolved external symbol DirectXFileCreate`

**Comment by gongminmin** [comment]
No, .def is for generating .lib or .a from .dll. It's not suppose to be used in cmake.
